
# lists news
# @name news
GET http://rvm.test/api/v1/news
Authorization: Bearer <token>
Content-Type: application/json
###

# @name user
GET http://rvm.test/api/user
Authorization: Bearer <token>
Content-Type: application/json
###